/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/opt/gettext-0.22.5"
#define EXEC_PREFIX "/opt/gettext-0.22.5"
#define BINDIR "/opt/gettext-0.22.5/bin"
#define SBINDIR "/opt/gettext-0.22.5/sbin"
#define LIBEXECDIR "/opt/gettext-0.22.5/libexec"
#define DATAROOTDIR "/opt/gettext-0.22.5/share"
#define DATADIR "/opt/gettext-0.22.5/share"
#define SYSCONFDIR "/opt/gettext-0.22.5/etc"
#define SHAREDSTATEDIR "/opt/gettext-0.22.5/com"
#define LOCALSTATEDIR "/opt/gettext-0.22.5/var"
#define RUNSTATEDIR "/opt/gettext-0.22.5/var/run"
#define INCLUDEDIR "/opt/gettext-0.22.5/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/opt/gettext-0.22.5/share/doc/gettext"
#define INFODIR "/opt/gettext-0.22.5/share/info"
#define HTMLDIR "/opt/gettext-0.22.5/share/doc/gettext"
#define DVIDIR "/opt/gettext-0.22.5/share/doc/gettext"
#define PDFDIR "/opt/gettext-0.22.5/share/doc/gettext"
#define PSDIR "/opt/gettext-0.22.5/share/doc/gettext"
#define LIBDIR "/opt/gettext-0.22.5/lib"
#define LISPDIR "/opt/gettext-0.22.5/share/emacs/site-lisp"
#define LOCALEDIR "/opt/gettext-0.22.5/share/locale"
#define MANDIR "/opt/gettext-0.22.5/share/man"
#define PKGDATADIR "/opt/gettext-0.22.5/share/gettext"
#define PKGINCLUDEDIR "/opt/gettext-0.22.5/include/gettext-tools"
#define PKGLIBDIR "/opt/gettext-0.22.5/lib/gettext-tools"
#define PKGLIBEXECDIR "/opt/gettext-0.22.5/libexec/gettext-tools"
